In [4]:
import numpy as np
import random
from time import sleep

def create_board():
    return np.zeros((3,3), dtype=int)

def possibilities(board):
    return [(i,j) for i in range(3) for j in range (3) if board [i][j]==0]

def random_place(board, player):
    loc = random.choice(possibilities(board))
    board[loc] = player
    return board

def human_place(board, player):
    while True:
        try:
            move_input = input(f"Player {player}, enter your move (row,col e.g., 1,2): ")
            row, col = map(int, move_input.split(','))

            row -= 1
            col -= 1

            if 0 <= row <= 2 and 0 <= col <= 2 and board[row][col] == 0:
                board[row][col] = player
                return board
            else:
                print("Invalid move. Try again.")
        except:
            print("Invalid input format. Please use 'row,col' (e.g., 1,2).")

def row_win(board, player):
    return any(all(cell==player for cell in row) for row in board)

def col_win(board, player):
    return any(all(row[i]==player for row in board) for i in range(3))

def diag_win(board, player):
    return all(board[i][i]==player for i in range(3)) or\
           all(board[i][2 - i] == player for i in range(3))

def evaluate(board):
    for player in [1,2]:
        if row_win(board,player) or col_win(board,player) or diag_win(board,player):
            return player
    return -1 if np.all(board!=0) else 0

def play_game_interactive():
    board, winner, move = create_board(), 0, 1
    print("\n--- New Game: Tic-Tac-Toe ---")
    print("You are Player 1 (1s). Computer is Player 2 (2s).")
    print("Input moves as 'row,col' (1,1 is top-left, 3,3 is bottom-right).")
    print(f"\nInitial Board:\n{board}")
    sleep(1)

    while winner == 0:
        if winner == 0 and len(possibilities(board)) > 0:
            print("\nYour Turn (Player 1):")
            board = human_place(board, 1)
            print(f"\n Board after Human move:\n{board}")
            sleep(1)
            move += 1
            winner = evaluate(board)

        if winner == 0 and len(possibilities(board)) > 0:
            print("\nComputer's Turn (Player 2):")
            board = random_place(board, 2)
            print(f"\n Board after Computer move:\n{board}")
            sleep(1)
            move += 1
            winner = evaluate(board)

    if winner == 1:
        print("\ Congratulations! You (Player 1) won!")
    elif winner == 2:
        print("\n The Computer (Player 2) won.")
    else:
        print("\nIt's a Draw!")

    return winner

print(f"\n Soooo....the Winner is {play_game_interactive()}")

<>:75: SyntaxWarning: invalid escape sequence '\ '
<>:75: SyntaxWarning: invalid escape sequence '\ '
/tmp/ipython-input-2767055287.py:75: SyntaxWarning: invalid escape sequence '\ '
  print("\ Congratulations! You (Player 1) won!")



--- New Game: Tic-Tac-Toe ---
You are Player 1 (1s). Computer is Player 2 (2s).
Input moves as 'row,col' (1,1 is top-left, 3,3 is bottom-right).

Initial Board:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Your Turn (Player 1):
Player 1, enter your move (row,col e.g., 1,2): 1,1

 Board after Human move:
[[1 0 0]
 [0 0 0]
 [0 0 0]]

Computer's Turn (Player 2):

 Board after Computer move:
[[1 2 0]
 [0 0 0]
 [0 0 0]]

Your Turn (Player 1):
Player 1, enter your move (row,col e.g., 1,2): 2,3

 Board after Human move:
[[1 2 0]
 [0 0 1]
 [0 0 0]]

Computer's Turn (Player 2):

 Board after Computer move:
[[1 2 0]
 [0 2 1]
 [0 0 0]]

Your Turn (Player 1):
Player 1, enter your move (row,col e.g., 1,2): 3,2

 Board after Human move:
[[1 2 0]
 [0 2 1]
 [0 1 0]]

Computer's Turn (Player 2):

 Board after Computer move:
[[1 2 0]
 [0 2 1]
 [2 1 0]]

Your Turn (Player 1):
Player 1, enter your move (row,col e.g., 1,2): 1,3

 Board after Human move:
[[1 2 1]
 [0 2 1]
 [2 1 0]]

Computer's Turn (Player 2):

 Board aft